- name: Gather EC2 facts
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:Type": "gameserver"
    aws_access_key: "{{ secrets.aws_access_key }}"
    aws_secret_key: "{{ secrets.aws_secret_key }}"
  register: ec2
- debug: var=ec2
- name: Terminate EC2 Instance(s)
  ec2:
    instance_ids: '{{ item.instance_id }}'
    state: absent
    region: "{{ region }}"
    aws_access_key: "{{ secrets.aws_access_key }}"
    aws_secret_key: "{{ secrets.aws_secret_key }}"
  with_items: "{{ ec2.instances }}"